spring:
  datasource:
    url: jdbc:postgresql://localhost:5429/assembleia
    username: dev
    password: dev
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jackson:
    date-format: dd-MM-yyyy
